# Generated by Django 5.2 on 2025-04-30 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=11)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('dataDeNascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('rendaMensal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('susep', models.CharField(max_length=50)),
                ('expiracaoDeVenda', models.DateField()),
                ('valorMinimoAporteInicial', models.FloatField()),
                ('valorMinimoAporteExtra', models.FloatField()),
                ('idadeDeEntrada', models.IntegerField()),
                ('idadeDeSaida', models.IntegerField()),
                ('carenciaInicialDeResgate', models.IntegerField()),
                ('carenciaEntreResgates', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aporte_inicial', models.FloatField()),
                ('data_contratacao', models.DateField()),
                ('saldo', models.FloatField(default=0)),
                ('ultima_data_resgate', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Aporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano')),
            ],
        ),
        migrations.CreateModel(
            name='Resgate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField()),
                ('data', models.DateField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.plano')),
            ],
        ),
    ]
