# Generated by Django 5.2 on 2025-04-30 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='ultima_data_resgate',
        ),
    ]
