# Generated by Django 5.2 on 2025-05-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_plano_saldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='saldo',
            field=models.FloatField(default=0),
        ),
    ]
